# Generated by Django 4.2.6 on 2023-11-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashnomics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='username',
        ),
    ]
