# Generated by Django 5.0 on 2023-12-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashnomics', '0003_remove_expensesform_cost_ent_chart_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsinvestments',
            name='money_after_y1',
        ),
        migrations.RemoveField(
            model_name='savingsinvestments',
            name='money_after_y5',
        ),
    ]
