# Generated by Django 5.0 on 2023-12-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashnomics', '0004_remove_savingsinvestments_money_after_y1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesform',
            name='version',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='incomeform',
            name='version',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='savingsinvestments',
            name='version',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
