# Generated by Django 5.0 on 2023-12-19 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashnomics', '0007_alter_expensesform_financial_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesform',
            name='financial_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cashnomics.financialmodel'),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomeform',
            name='financial_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='cashnomics.financialmodel'),
        ),
        migrations.AlterField(
            model_name='savingsinvestments',
            name='financial_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='cashnomics.financialmodel'),
        ),
    ]
