# Generated by Django 5.0 on 2023-12-19 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashnomics', '0008_alter_expensesform_financial_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesform',
            name='financial_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cashnomics.financialmodel'),
        ),
        migrations.AlterField(
            model_name='incomeform',
            name='financial_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='cashnomics.financialmodel'),
        ),
        migrations.AlterField(
            model_name='savingsinvestments',
            name='financial_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='cashnomics.financialmodel'),
        ),
    ]
