# Generated by Django 5.0 on 2023-12-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashnomics', '0010_remove_expensesform_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesform',
            name='cost_groceries',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expensesform',
            name='cost_other',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expensesform',
            name='cost_sh_bills',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expensesform',
            name='cost_travel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expensesform',
            name='money_aftercosts',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='incomeform',
            name='income_after_tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='incomeform',
            name='salary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='savingsinvestments',
            name='etf_amt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='savingsinvestments',
            name='etf_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='savingsinvestments',
            name='savings_amt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='savingsinvestments',
            name='savings_rate',
            field=models.FloatField(),
        ),
    ]
